### PR TITLE
Migrate prelude

### PR DESCRIPTION
**Pull request by Danfs64**
I'm slowly taking the structures on HVM's [prelude](github.com/Kindelia/prelude) and translating them to Kind2.

I opened this draft so there is a proper place for me to voice my doubts and for people to suggest stuff

### CODE REVIEW

**Comment by Danfs64** [comment]
Opening up the "voice my doubts" part:

1. I think it would make sense for ListZipper to be inside List (as List.Zipper, like Bits.Map inside Bits)
2. There are (for now) 3 different kind of Heaps. Instead of having these 3 folders, we could:
  * Maybe have a Heap folder, and inside it having a folder for each?
  * Maybe discard some of the Heaps? I think (?) some of them are more educational type of heaps instead of actually efficient ones

**Comment by steinerkelvin** [comment]
What _is_ a ListZipper? 🧐

**Comment by Danfs64** [comment]
[Wikipedia link](https://en.wikipedia.org/wiki/Zipper_(data_structure)). As far as I'm aware, it is basically a structure to optimize read/write access to the elements of a list where you want to arbitrarily traverse either to the left or to the right (or a combination of both). Incidentally, it also allows for a efficient (O(1)) reverse operation. (reversing the Zipper and converting it back to List is still O(n) thou)
@samueldurantes was the one that originally implemented it on HVM, I believe, so he might have a better explanation

**Comment by VictorTaelin** [comment]
Is this complete / mergeable? Can we add the datatypes to a /Data dir?

**Comment by Danfs64** [comment]
I'll put them on the /Data dir myself. I still intent to generalize at least the heaps (make them accept any type as values, provided of a comparison function). After that is done (hopefully by Friday), I'll undraft the PR

**Comment by Danfs64** [comment]
Okay, I had some trouble generalizing the Heap value Type. Since all of those heaps are supposed to be mergeable, having an arbitrary comparison function would break that, because you can't check if both heaps have equivalent comparison functions, therefore you can't know if they are mergeable.

With that said, the PR is ready to be merged

**Comment by VictorTaelin** [comment]
Nice! Thank you. This code is great. The comments are on point too.

**Pull request merged**
